using System.Diagnostics;
using System.Reflection;
using System.Reflection.Metadata;
using System.Reflection.PortableExecutable;
using System.Runtime.CompilerServices;
using System.Text;

using OneShot.Web.Secrets;

namespace OneShot.Tests;

// SecretRecordTests and ConsumedSecretTests already pin the two types that hold secret material today. These
// are the checks that keep holding as the code grows: a sweep over every type in the assembly rather than the
// two we happen to know about, and a read of the compiled metadata rather than of the source.
[Trait("Threat", "T1")]
[Trait("Threat", "T9")]
public sealed class MemoryHygieneTests
{
    private static readonly Assembly Web = typeof(Program).Assembly;

    // Any symmetric cipher the server could decrypt with. AesGcm is the one the client uses, and the whole
    // zero-knowledge claim rests on the server having no way to reach it.
    private static readonly string[] ForbiddenCryptoTypes =
    [
        "Aes",
        "AesGcm",
        "AesCcm",
        "AesManaged",
        "AesCryptoServiceProvider",
        "ChaCha20Poly1305",
        "TripleDES",
        "TripleDESCryptoServiceProvider",
        "DES",
        "RC2",
        "SymmetricAlgorithm",
        "ICryptoTransform",
        "CryptoStream",
    ];

    [Fact]
    public void TheWebAssembly_ReferencesNoTypeItCouldDecryptWith()
    {
        var referenced = CryptographyTypeReferences();

        // A positive control: if the metadata read came back empty this test would pass while checking
        // nothing, so the types the app genuinely does use must show up first.
        Assert.Contains("RandomNumberGenerator", referenced);
        Assert.Contains("CryptographicOperations", referenced);

        foreach (var forbidden in ForbiddenCryptoTypes)
        {
            Assert.DoesNotContain(forbidden, referenced);
        }
    }

    [Fact]
    public void TheWebAssembly_ReferencesNothingThatCouldPersistKeyMaterialToDisk()
    {
        using var stream = File.OpenRead(Web.Location);
        using var portable = new PEReader(stream);
        var reader = portable.GetMetadataReader();

        var namespaces = reader.TypeReferences
            .Select(reader.GetTypeReference)
            .Select(type => reader.GetString(type.Namespace))
            .ToHashSet(StringComparer.Ordinal);

        Assert.Contains("System.Security.Cryptography", namespaces);
        // The Data Protection key ring is the classic way secret material reaches disk; the app uses the
        // ephemeral provider (task 5) and must never reference the file-system or registry repositories.
        Assert.DoesNotContain("Microsoft.AspNetCore.DataProtection.Repositories", namespaces);
    }

    public static TheoryData<string> SecretBearingTypes => new()
    {
        nameof(SecretRecord),
        nameof(ConsumedSecret),
    };

    [Theory]
    [MemberData(nameof(SecretBearingTypes))]
    public void ATypeHoldingSecretMaterial_RendersNoneOfItWhenPrinted(string typeName)
    {
        const string canary = "CANARY-BUFFER-8b41c7de-padding-padding-pad48";
        var buffer = Encoding.ASCII.GetBytes(canary);
        var nonce = Encoding.ASCII.GetBytes("CANARYNONCE1");
        object instance = typeName == nameof(SecretRecord)
            ? new SecretRecord("abcdefghijklmnopqrstuv", buffer, nonce, DateTimeOffset.UnixEpoch, DateTimeOffset.UnixEpoch.AddHours(1))
            : new ConsumedSecret(buffer, nonce);

        var printed = instance.ToString() ?? string.Empty;

        // Every shape the bytes could take in a log line that interpolated the object.
        Assert.DoesNotContain(canary, printed, StringComparison.Ordinal);
        Assert.DoesNotContain(Convert.ToBase64String(buffer), printed, StringComparison.Ordinal);
        Assert.DoesNotContain(Convert.ToHexString(buffer), printed, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("CANARYNONCE1", printed, StringComparison.Ordinal);
    }

    [Fact]
    public void EveryTypeInTheAssemblyThatHoldsBytes_CannotRenderThem()
    {
        var offenders = new List<string>();

        foreach (var type in BufferBearingTypes())
        {
            // A record's ToString is generated by the compiler and prints every member, so a record holding a
            // byte[] prints it the moment anyone interpolates it into a log line. "Declares a ToString" is not
            // enough to rule that out, because the generated one is declared on the record too — it has to be
            // hand-written, which is what the absence of CompilerGenerated means here.
            var toString = type.GetMethod(nameof(ToString), BindingFlags.Public | BindingFlags.Instance, Type.EmptyTypes);
            if (toString?.DeclaringType != type)
            {
                offenders.Add($"{type.Name} holds a byte[] but does not declare its own ToString");
            }
            else if (toString.IsDefined(typeof(CompilerGeneratedAttribute), inherit: false))
            {
                offenders.Add($"{type.Name} holds a byte[] and leaves ToString to the compiler, which prints every member");
            }

            if (type.IsPublic)
            {
                offenders.Add($"{type.Name} holds a byte[] and is public, so it could be bound or serialised from outside");
            }

            foreach (var attribute in type.GetCustomAttributes<DebuggerDisplayAttribute>())
            {
                offenders.Add($"{type.Name} has a DebuggerDisplay: {attribute.Value}");
            }

            Assert.Empty(type.GetCustomAttributes<DebuggerTypeProxyAttribute>());
        }

        Assert.Empty(offenders);
    }

    [Fact]
    public void TheSweepAboveActuallyFindsTheTypesItIsMeantTo()
    {
        // Without this, a filter that quietly matched nothing would make the sweep pass by inspecting nothing.
        var found = BufferBearingTypes().Select(type => type.Name).ToList();

        Assert.Contains(nameof(SecretRecord), found);
        Assert.Contains(nameof(ConsumedSecret), found);
    }

    private static List<Type> BufferBearingTypes()
    {
        return [.. Web.GetTypes()
            .Where(type => !type.IsDefined(typeof(CompilerGeneratedAttribute), inherit: false))
            .Where(type => type.GetFields(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance)
                    .Any(field => field.FieldType == typeof(byte[]))
                || type.GetProperties(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance)
                    .Any(property => property.PropertyType == typeof(byte[])))];
    }

    // Read from the compiled assembly rather than the source: a source scan misses a type reached through a
    // using alias, a fully qualified name, or a helper in another file.
    private static HashSet<string> CryptographyTypeReferences()
    {
        using var stream = File.OpenRead(Web.Location);
        using var portable = new PEReader(stream);
        var reader = portable.GetMetadataReader();

        return [.. reader.TypeReferences
            .Select(reader.GetTypeReference)
            .Where(type => reader.GetString(type.Namespace).StartsWith("System.Security.Cryptography", StringComparison.Ordinal))
            .Select(type => reader.GetString(type.Name))];
    }
}
